import pandas as pd
import numpy as np
import os
import json

def run_backtest(ticker, days=365):
    """
    Simulates a Buy/Sell strategy based on Volatility changes over the last 'days'.
    
    Strategy:
    - BUY when Volatility drops > 5% (Stabilizing)
    - SELL when Volatility rises > 5% (Risk increasing)
    - HOLD otherwise
    
    Returns:
        dict: Performance metrics and equity curves.
    """
    try:
        # 1. Load Data from existing JSON (generated by analysis scripts)
        # We rely on the detailed JSON which contains 'normalized_price' and 'volatility_history'
        file_path = os.path.join(os.path.dirname(__file__), 'data', 'stocks', f'{ticker}.json')
        
        if not os.path.exists(file_path):
            return {'error': 'Data not found for backtesting.'}
            
        with open(file_path, 'r') as f:
            data = json.load(f)
            
        # Convert list to DataFrame
        df = pd.DataFrame({
            'date': data['dates'],
            'price': data['normalized_price'], # Base 100
            'volatility': data['volatility_history']
        })
        
        # Filter for the simulation period (last N days)
        df['date'] = pd.to_datetime(df['date'])
        df = df.sort_values('date').tail(days).reset_index(drop=True)
        
        if len(df) < 10:
             return {'error': 'Not enough data points for backtest.'}

        # 2. Simulation Variables
        initial_capital = 10000
        cash = initial_capital
        holdings = 0
        
        # Lists for tracking
        strategy_equity = []
        buy_hold_equity = []
        signals = [] # For visualization overlap
        
        # Buy & Hold Logic (Buy at start, hold till end)
        bh_shares = initial_capital / df.iloc[0]['price']
        
        # 3. Iterate through days
        for i in range(1, len(df)):
            current_date = df.iloc[i]['date'].strftime('%Y-%m-%d')
            current_price = df.iloc[i]['price']
            current_vol = df.iloc[i]['volatility']
            prev_vol = df.iloc[i-1]['volatility']
            
            # Change in volatility
            vol_change_pct = (current_vol - prev_vol) / prev_vol
            
            signal = "HOLD"
            
            # --- Strategy Logic ---
            # BUY if volatility drops significantly (> 5%) and we have cash
            if vol_change_pct < -0.05 and cash > 0:
                signal = "BUY"
                shares_to_buy = cash / current_price
                holdings += shares_to_buy
                cash = 0
                signals.append({'date': current_date, 'type': 'BUY', 'price': current_price})
                
            # SELL if volatility spikes (> 5%) and we have holdings
            elif vol_change_pct > 0.05 and holdings > 0:
                signal = "SELL"
                cash = holdings * current_price
                holdings = 0
                signals.append({'date': current_date, 'type': 'SELL', 'price': current_price})
            
            # Calculate Daily Equity
            current_val = cash + (holdings * current_price)
            strategy_equity.append(round(current_val, 2))
            
            # Buy & Hold Equity
            buy_hold_equity.append(round(bh_shares * current_price, 2))
            
        # 4. Final Metrics
        final_strategy = strategy_equity[-1]
        final_bh = buy_hold_equity[-1]
        
        strategy_return = ((final_strategy - initial_capital) / initial_capital) * 100
        bh_return = ((final_bh - initial_capital) / initial_capital) * 100
        
        return {
            'ticker': ticker,
            'period_days': days,
            'initial_capital': initial_capital,
            'final_strategy_value': final_strategy,
            'final_buy_hold_value': final_bh,
            'strategy_return_pct': round(strategy_return, 2),
            'buy_hold_return_pct': round(bh_return, 2),
            'dates': [d.strftime('%Y-%m-%d') for d in df['date'].tolist()[1:]], # Skip first day
            'strategy_curve': strategy_equity,
            'buy_hold_curve': buy_hold_equity,
            'signals': signals
        }

    except Exception as e:
        return {'error': str(e)}
